command: [
  "uvicorn",
  "server.app:app"
]
env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '808413184331923'
  - name: 'LOW_ACCURACY_RESULTS_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/experiments/808413184331923/evaluation-runs?selectedRunUuid=3d8d8ba39e6e4171bb4abb262c0f7b20&compareToRunUuid=faf78ffb1a0d468987446f51efe540cd'
  - name: 'REGRESSION_RESULTS_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/experiments/808413184331923/evaluation-runs?selectedRunUuid=17707b3e49254f8989204b4e6167fd5e&compareToRunUuid=27cc290a6fbb4301b780308b75d53b11'
  - name: 'METRICS_RESULT_URL'
    value: 'placeholder-metrics-url'
  - name: 'LLM_MODEL'
    value: 'databricks-claude-3-7-sonnet'
  - name: 'UC_CATALOG'
    value: 'amine_elhelou'
  - name: 'UC_SCHEMA'
    value: 'mlflow3_demo_dev'
  - name: 'MLFLOW_ENABLE_ASYNC_TRACE_LOGGING'
    value: 'false'
  - name: 'PROMPT_NAME'
    value: 'email_generation'
  - name: 'PROMPT_ALIAS'
    value: 'production'
  - name: 'REGRESSION_BASELINE_RUN_ID'
    value: '27cc290a6fbb4301b780308b75d53b11'
  - name: 'FIX_QUALITY_BASELINE_RUN_ID'
    value: 'faf78ffb1a0d468987446f51efe540cd'
  - name: 'SAMPLE_LABELING_SESSION_ID'
    value: '4fbfc8dd-b938-4374-8b71-c64b4c3422f5'
  - name: 'SAMPLE_REVIEW_APP_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/review-v2/b5d43eab3001483f9bfe33c71e20d37d/tasks/labeling/4fbfc8dd-b938-4374-8b71-c64b4c3422f5'
  - name: 'SAMPLE_LABELING_TRACE_ID'
    value: 'tr-f151a259953e10fe45e528b1e3985f30'
  - name: 'SAMPLE_TRACE_ID'
    value: 'tr-4c5cd254cdeedd5535694ad50d17d081'
  - name: 'LHA_SOURCE_CODE_PATH'
    value: '/Workspace/Users/amine.elhelou@databricks.com/mlflow-demo-app-aeh-dev'
  - name: 'NOTEBOOK_URL_0_demo_overview'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184332323'
  - name: 'NOTEBOOK_URL_1_observe_with_traces'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184332196'
  - name: 'NOTEBOOK_URL_2_create_quality_metrics'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184332258'
  - name: 'NOTEBOOK_URL_3_find_fix_quality_issues'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184332189'
  - name: 'NOTEBOOK_URL_4_human_review'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184332245'
  - name: 'NOTEBOOK_URL_5_production_monitoring'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/808413184332233'
