command: [
  "uvicorn",
  "server.app:app"
]
env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '3301487308209184'
  - name: 'LOW_ACCURACY_RESULTS_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/experiments/3301487308209184/evaluation-runs?selectedRunUuid=08023567bb3f419d8ee4ceacd19b056e&compareToRunUuid=c2ff97461e7d4d33bfb26e1aca87d711'
  - name: 'REGRESSION_RESULTS_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/experiments/3301487308209184/evaluation-runs?selectedRunUuid=d6c4172d30804c6db307b2e389747e73&compareToRunUuid=29dbebbab7ae4bec92d16cca9fdfac52'
  - name: 'METRICS_RESULT_URL'
    value: 'placeholder-metrics-url'
  - name: 'LLM_MODEL'
    value: 'databricks-claude-sonnet-4-6'
  - name: 'UC_CATALOG'
    value: 'amine_elhelou'
  - name: 'UC_SCHEMA'
    value: 'mlflow3_demo_dev'
  - name: 'MLFLOW_ENABLE_ASYNC_TRACE_LOGGING'
    value: 'false'
  - name: 'MLFLOW_TRACING_DESTINATION'
    value: 'amine_elhelou.mlflow3_demo_dev'
  - name: 'SQL_WAREHOUSE_ID'
    value: '862f1d757f0424f7'
  - name: 'PROMPT_NAME'
    value: 'email_generation'
  - name: 'PROMPT_ALIAS'
    value: 'production'
  - name: 'REGRESSION_BASELINE_RUN_ID'
    value: '29dbebbab7ae4bec92d16cca9fdfac52'
  - name: 'FIX_QUALITY_BASELINE_RUN_ID'
    value: 'c2ff97461e7d4d33bfb26e1aca87d711'
  - name: 'SAMPLE_LABELING_SESSION_ID'
    value: '5b06d11c-02e9-40cf-b13c-bc37f295c73b'
  - name: 'SAMPLE_REVIEW_APP_URL'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/ml/review-v2/0c9357c78d044632b2d7418877401bab/tasks/labeling/5b06d11c-02e9-40cf-b13c-bc37f295c73b'
  - name: 'SAMPLE_LABELING_TRACE_ID'
    value: 'trace:/amine_elhelou.mlflow3_demo_dev/9f09339f35d714a8ac727dadc30764e0'
  - name: 'SAMPLE_TRACE_ID'
    value: 'trace:/amine_elhelou.mlflow3_demo_dev/4389b4c4bfc7a7c9c13612a3a8d4b6b0'
  - name: 'LHA_SOURCE_CODE_PATH'
    value: '/Workspace/Users/amine.elhelou@databricks.com/mlflow-demo-app-dev-aeh'
  - name: 'NOTEBOOK_URL_0_demo_overview'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/3301487308210919'
  - name: 'NOTEBOOK_URL_1_observe_with_traces'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/3301487308210915'
  - name: 'NOTEBOOK_URL_2_create_quality_metrics'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/3301487308210932'
  - name: 'NOTEBOOK_URL_3_find_fix_quality_issues'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/3301487308210918'
  - name: 'NOTEBOOK_URL_4_human_review'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/3301487308210819'
  - name: 'NOTEBOOK_URL_5_production_monitoring'
    value: 'https://e2-demo-field-eng.cloud.databricks.com/editor/notebooks/3301487308210808'
